### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hwj0629** [EdwinChua/clash#4]
i have change tag and token
but it shows nothing https://www.hwj6.cn/clash/

**Comment by EdwinChua** [comment]
Seems like you solved it? The link works, although it is loading my clan's data.

What you need to do to get your clan data is run `phpScripts/coc.php` once. (This gets latest data and saves it).

To get the data automatically, and on a regular basis, call the `coc.php` script with a [cron job (linux)](https://code.tutsplus.com/tutorials/scheduling-tasks-with-cron-jobs--net-8800) or similar.

**Comment by hwj0629** [comment]
when i run [https://www.hwj6.cn/clash/phpScripts/coc.php](https://www.hwj6.cn/clash/phpScripts/coc.php) it shows error 500...

**Comment by EdwinChua** [comment]
Make sure you have the following code at the top of your file:

```php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

Enter the error you encountered.

**Comment by hwj0629** [comment]
`ini_set（' display_errors '，1）; 
ini_set（' display_startup_errors '，1）; 
error_reporting（E_ALL）;
<?php

header('Content-Type: application/json; charset=UTF-8');
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$my_file = '../saved-data/clan-info.json';

$clantag = "#Y988UYVV";

//deployment key
$token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjI4MWQzYWZjLTJiMGYtNGMzZS05ZTljLTA5NTFmNjhhZjhjMyIsImlhdCI6MTUyNTUzMTkwMiwic3ViIjoiZGV2ZWxvcGVyLzI3Njc4MTk5LWViMTQtY2E1Ny0wZWViLWI2MjQ2ZmM5OGY5NiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEyMy4yMDYuODcuMTIwIl0sInR5cGUiOiJjbGllbnQifV19.4AceUgIb7xo8zyli6j_KWy6Dg1XpLegGXWcbKKfztO_8F4podGQKDITXMmKKQrWTNn3VDxATxnAwkHsKkcvNjg";

//test env key
//$token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjgyYjQzZDQwLTAyYzMtNDAxZC04MjIxLWY5NjA3ZTYxNTNlYyIsImlhdCI6MTUwOTMzMzc4MCwic3ViIjoiZGV2ZWxvcGVyL2UwMTcwNDEzLWZlNjQtYTg5OC03OTMwLWZlYTA4MjRmOTk5YyIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE5Mi4xMjIuMTMxLjEzIl0sInR5cGUiOiJjbGllbnQifV19.cdJp9ZSYl6wYnR4xfPIX39c-VpsVfMUoBKMYmI-zcxUrx2fOAbktiv070MjyxoTYI4zLQUeDKQJ7KVdNqIFQ6w";


$url_clan = "https://api.clashofclans.com/v1/clans/" . urlencode($clantag);

$ch = curl_init($url_clan);

$headr = array();
$headr[] = "Accept: application/json";
$headr[] = "Authorization: Bearer ".$token;

curl_setopt($ch, CURLOPT_HTTPHEADER, $headr);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 

$res = curl_exec($ch);
$clan_data_arr = json_decode($res, true);
curl_close($ch);
//echo $res;

$clan_player_data_arr = array();

$count = count($clan_data_arr["memberList"]);
//echo $count;
for ($i = 0; $i < $count; $i++)
{
	$dataIsOk = false;
	$noOfTries = 0;

	while($dataIsOk == false) 
	{
		$url_player = "https://api.clashofclans.com/v1/players/" . urlencode($clan_data_arr["memberList"][$i]["tag"]);
		$ch2 = curl_init($url_player);
		curl_setopt($ch2, CURLOPT_HTTPHEADER, $headr);
		curl_setopt($ch2, CURLOPT_SSL_VERIFYHOST, false);
		curl_setopt($ch2, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($ch2, CURLOPT_RETURNTRANSFER, 1); 

		$res_player = curl_exec($ch2);
		$result =  json_decode($res_player,true);
		if ($result["reason"] == null) // check if data recieved is ok ( eg. {reason : "unknown exeception"})
		{
			$dataIsOk = true;
		}
		else
		{
			$noOfTries++;
			if ($noOfTries > 3)
			{
				$dataIsOk = true; // skip after trying 3 times
			}
		}
	}
	array_push($clan_player_data_arr, json_decode($res_player));
}

include './currentdate.php';

$reponse_arr = array("updatedOn"=>$date, "clan" => $clan_data_arr,"players" => $clan_player_data_arr);

$reponse_arr = json_encode($reponse_arr);

$handle = fopen($my_file, 'w') or die('Cannot open file:  '.$my_file);
file_put_contents($my_file, $reponse_arr);

echo $reponse_arr;


?>
`

**Comment by hwj0629** [comment]
ini_set（' display_errors '，1）; 
ini_set（' display_startup_errors '，1）; 
error_reporting（E_ALL）;
<?php

header('Content-Type: application/json; charset=UTF-8');
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$my_file = '../saved-data/clan-info.json';

$clantag = "#Y988UYVV";

//deployment key
$token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjI4MWQzYWZjLTJiMGYtNGMzZS05ZTljLTA5NTFmNjhhZjhjMyIsImlhdCI6MTUyNTUzMTkwMiwic3ViIjoiZGV2ZWxvcGVyLzI3Njc4MTk5LWViMTQtY2E1Ny0wZWViLWI2MjQ2ZmM5OGY5NiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEyMy4yMDYuODcuMTIwIl0sInR5cGUiOiJjbGllbnQifV19.4AceUgIb7xo8zyli6j_KWy6Dg1XpLegGXWcbKKfztO_8F4podGQKDITXMmKKQrWTNn3VDxATxnAwkHsKkcvNjg";

//test env key
//$token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjgyYjQzZDQwLTAyYzMtNDAxZC04MjIxLWY5NjA3ZTYxNTNlYyIsImlhdCI6MTUwOTMzMzc4MCwic3ViIjoiZGV2ZWxvcGVyL2UwMTcwNDEzLWZlNjQtYTg5OC03OTMwLWZlYTA4MjRmOTk5YyIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE5Mi4xMjIuMTMxLjEzIl0sInR5cGUiOiJjbGllbnQifV19.cdJp9ZSYl6wYnR4xfPIX39c-VpsVfMUoBKMYmI-zcxUrx2fOAbktiv070MjyxoTYI4zLQUeDKQJ7KVdNqIFQ6w";


$url_clan = "https://api.clashofclans.com/v1/clans/" . urlencode($clantag);

$ch = curl_init($url_clan);

$headr = array();
$headr[] = "Accept: application/json";
$headr[] = "Authorization: Bearer ".$token;

curl_setopt($ch, CURLOPT_HTTPHEADER, $headr);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 

$res = curl_exec($ch);
$clan_data_arr = json_decode($res, true);
curl_close($ch);
//echo $res;

$clan_player_data_arr = array();

$count = count($clan_data_arr["memberList"]);
//echo $count;
for ($i = 0; $i < $count; $i++)
{
	$dataIsOk = false;
	$noOfTries = 0;

	while($dataIsOk == false) 
	{
		$url_player = "https://api.clashofclans.com/v1/players/" . urlencode($clan_data_arr["memberList"][$i]["tag"]);
		$ch2 = curl_init($url_player);
		curl_setopt($ch2, CURLOPT_HTTPHEADER, $headr);
		curl_setopt($ch2, CURLOPT_SSL_VERIFYHOST, false);
		curl_setopt($ch2, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($ch2, CURLOPT_RETURNTRANSFER, 1); 

		$res_player = curl_exec($ch2);
		$result =  json_decode($res_player,true);
		if ($result["reason"] == null) // check if data recieved is ok ( eg. {reason : "unknown exeception"})
		{
			$dataIsOk = true;
		}
		else
		{
			$noOfTries++;
			if ($noOfTries > 3)
			{
				$dataIsOk = true; // skip after trying 3 times
			}
		}
	}
	array_push($clan_player_data_arr, json_decode($res_player));
}

include './currentdate.php';

$reponse_arr = array("updatedOn"=>$date, "clan" => $clan_data_arr,"players" => $clan_player_data_arr);

$reponse_arr = json_encode($reponse_arr);

$handle = fopen($my_file, 'w') or die('Cannot open file:  '.$my_file);
file_put_contents($my_file, $reponse_arr);

echo $reponse_arr;


?>

**Comment by hwj0629** [comment]
could you download https://www.hwj6.cn/clash/phpScripts/coc.php to see the code..

**Comment by EdwinChua** [comment]
@hwj0629 a PHP script is server-side code. It cannot be downloaded from another browser.

Try creating a new file with the following contents, and try to access it:

```php
<?php

// Show all information, defaults to INFO_ALL
phpinfo();
```

**Comment by hwj0629** [comment]
https://hwj6.cn/php.php
`<?php

// Show all information, defaults to INFO_ALL
phpinfo();`

**Comment by hwj0629** [comment]
> <?php

// Show all information, defaults to INFO_ALL
phpinfo();

**Comment by EdwinChua** [comment]
Hmm.. Likely, you have made a mistake in your PHP code somewhere, as phpinfo() is working.

Try following [the guide here](https://blog.crazy.technology/post/Clash-of-Clans---How-to-use-the-Web-API-570dd2b2) and see if you can get it to work first.

**Comment by EdwinChua** [comment]
housekeeping
